version: 3.0.0
services:
  db:
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=MealReview
#    volumes:
#        - ./database:/docker-entrypoint-initdb.d

  phpmyadmin:
  # Username: root
  # Password: P@ssw0rd
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - db

  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=P@ssw0rd
      - MINIO_DEFAULT_BUCKETS=review-image

